### ISSUE TITLE
Enforce HTTPS

### ISSUE THREAD

**Issue by konklone** [0xabad1dea/0xabad1dea.github.com#5]
GitHub now lets you enforce HTTPS for `*.github.io` domains:

https://github.com/blog/2186-https-for-github-pages

The site already works over HTTPS without errors: https://0xabad1dea.github.io So this should be a trivial fix.

![support page](https://help.github.com/assets/images/help/pages/enforce-https-checkbox.png)

**Comment by 0xabad1dea** [comment]
thank you for reminding me. I read the announcement but was in the middle of something at the time and forgot. It should be on now.

**Comment by konklone** [comment]
Awesome, thank you! :smiley_cat:
